// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221219000925_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseHiLo(modelBuilder, "EntityFrameworkHiLoSequence");

            modelBuilder.HasSequence("EntityFrameworkHiLoSequence")
                .IncrementsBy(10);

            modelBuilder.Entity("WebApi.Data.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "pizza"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "roll"
                        });
                });

            modelBuilder.Entity("WebApi.Data.Entities.OrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalSum")
                        .HasColumnType("money");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebApi.Data.Entities.OrderProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("WebApi.Data.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Consist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Consist = "mozzarella, mushrooms, salami, pesto sauce, tomato sauce, oregano",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2021/04/svjatoi-diablo-1.jpg.webp",
                            Price = 245m,
                            Title = "Pizza Saint Diablo",
                            Weight = 870.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Consist = "Pepperoni, hunting sausages, feta, olives, sriracha, mozzarella, oregano, tomato sauce",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2014/08/pepperoni.jpg.webp",
                            Price = 235m,
                            Title = "Pepperoni",
                            Weight = 800.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Consist = "mozzarella, hunting sausages, bacon, boiled pork, blue onion, tomato sauce, parsley, oregano",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2014/08/mjasnoj-bum.jpg.webp",
                            Price = 245m,
                            Title = "Pizza Boom of meat",
                            Weight = 850.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Consist = "mozzarella, chicken fillet, hunting sausages, champignons, parsley, ham, tomato sauce, oregano",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2014/08/evropejskaja.jpg.webp",
                            Price = 149m,
                            Title = "European",
                            Weight = 550.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Consist = "mozzarella, salmon, mussels, squid, tomato, lemon, pesto, oregano, tomato sauce",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2014/08/dary-morja.jpg.webp",
                            Price = 229m,
                            Title = "Seafood",
                            Weight = 550.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Consist = "mozzarella, ham, olives, tomatoes, parsley, mushrooms, oregano, tomato sauce",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2015/09/vechtchina-griby.jpg.webp",
                            Price = 239m,
                            Title = "Pizza with ham and mushrooms",
                            Weight = 900.0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Consist = "mozzarella, pineapple, chicken fillet, oregano, parsley, tomato sauce",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2014/08/tropikano-1.jpg.webp",
                            Price = 285m,
                            Title = "Pizza Life",
                            Weight = 900.0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Consist = "Feta, mozzarella, broccoli, olives, olives, bell peppers, tomatoes, mars onion, oregano, tomato sauce",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2021/04/vegetarianskaja-nju.jpg.webp",
                            Price = 159m,
                            Title = "Vegetarian",
                            Weight = 550.0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Consist = "mozzarella, boiled pork, salami, hunting sausages, ham, bacon, olives, oregano, tomato sauce",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2014/08/sbornaja-mjasnaja.jpg.webp",
                            Price = 245m,
                            Title = "Team Meat",
                            Weight = 850.0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Consist = "mozzarella, dorblu cheese, parmesan, hard cheese, bechamel sauce, oregano",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2015/09/4-syra.jpg.webp",
                            Price = 210m,
                            Title = "4 Cheeses",
                            Weight = 450.0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Consist = "ham, salami, Parmesan cheese, hard cheese, mozzarella, Dorblu cheese, mushrooms, tomatoes, Bechamel sauce, tomato sauce",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2022/09/2-dabl-panch-169-245-grn.jpg.webp",
                            Price = 169m,
                            Title = "Double Punch",
                            Weight = 500.0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Consist = "Veal sous-vide, salami, hunting sausages, chicken fillet, Dorblu cheese, parmesan, mozzarella, hard cheese, oregano, tomato sauce",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2021/04/4-mjasa-1.jpg.webp",
                            Price = 240m,
                            Title = "4 Meats",
                            Weight = 750.0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Consist = "butter, takuan, cucumber, bell pepper, mayonnaise",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2022/09/134-vilnii-165.jpg.webp",
                            Price = 165m,
                            Title = "Free",
                            Weight = 230.0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Consist = "salmon, shrimps, cream cheese, cucumber, spice sauce, batter, panko crackers",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2022/09/127-krevetkovi-kulki-199.jpg.webp",
                            Price = 199m,
                            Title = "Shrimp Balls",
                            Weight = 240.0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Consist = "smoked chicken, cream cheese, pineapple, mayonnaise, cheddar cheese, unagi sauce",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2022/09/102-gavaiskii-159-grn.jpg.webp",
                            Price = 159m,
                            Title = "Hawaiian",
                            Weight = 290.0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Consist = "smoked salmon, chuka, cucumber, bell pepper, iceberg lettuce, cheddar cheese, spice sauce, french onion",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2022/09/93-spring-fish-165-grn.jpg.webp",
                            Price = 165m,
                            Title = "Spring Fish",
                            Weight = 200.0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Consist = "cocktail shrimp, salmon, takuan, pumpkin, cream cheese, batter, panko crackers, spice sauce, unagi sauce, peanuts",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2022/09/50-unagi-kranch-219-grn.jpg.webp",
                            Price = 219m,
                            Title = "Unagi Crunch",
                            Weight = 300.0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Consist = "panko shrimp, eel, salmon, tuna, tiger shrimp, cream cheese, iceberg lettuce, scrambled eggs, spice sauce, unagi sauce, nachos",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2022/09/57-4-ribi-275-grn-ot-shefa.jpg.webp",
                            Price = 275m,
                            Title = "4 Fishes",
                            Weight = 300.0
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Consist = "salmon, takuan, scrambled eggs, nachos, mayonnaise, cheddar cheese, unag sauce",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2022/09/68-losos-na-grili-225-grn.jpg.webp",
                            Price = 225m,
                            Title = "Grilled Salmon",
                            Weight = 300.0
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Consist = "pumpkin, takuan, chuka, bell pepper, cream cheese",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2022/09/134-vilnii-165.jpg.webp",
                            Price = 119m,
                            Title = "Vegetus",
                            Weight = 220.0
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Consist = "salmon, snow crab, cream cheese, cucumber, scrambled eggs, tempura, panko crackers, spice sauce",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2022/06/2-vulkan-900h600.jpg.webp",
                            Price = 185m,
                            Title = "Volcano",
                            Weight = 290.0
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Consist = "cream cheese, salmon sous-vide, pink salmon, butterfish, cucumber, panko crackers, green onion, tempura, spice sauce",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2022/06/kopchenyj-losos-900h600-2.jpg.webp",
                            Price = 225m,
                            Title = "Tempura Mix Fish",
                            Weight = 280.0
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Consist = "unagi perch, cream cheese, cucumber, unagi sauce, spice sauce",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2021/12/unagi-grin.jpg.webp",
                            Price = 145m,
                            Title = "Philadelphia Unagi Green",
                            Weight = 225.0
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Consist = "salmon, cream cheese, pear, cheddar cheese, mayonnaise, sriracha sauce, unagi sauce",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2022/09/zapechena-filadelfija-nova-2.jpg.webp",
                            Price = 159m,
                            Title = "Baked Philadelphia",
                            Weight = 260.0
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            Consist = "smoked salmon, scrambled eggs, toaster cheese, cream cheese, cucumber, spice sauce",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2022/06/3-dabl-chiz-900h600.jpg.webp",
                            Price = 179m,
                            Title = "Double Cheese",
                            Weight = 235.0
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            Consist = "chicken, cream cheese, pear, cheddar cheese, mayonnaise, sesame, french onion, sriracha sauce, unagi sauce",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2022/08/zapechennaja-kurochka-grusha.jpg.webp",
                            Price = 159m,
                            Title = "Baked Chicken Pear",
                            Weight = 310.0
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            Consist = "unagi perch, salmon, cream cheese, panko crackers, tempura batter, unagi sauce",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2016/02/unagi-tempura-2.jpg.webp",
                            Price = 185m,
                            Title = "Unagi Tempura",
                            Weight = 280.0
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Consist = "salmon, cream cheese, scrambled eggs, cheddar cheese, mayonnaise, sesame, sriracha sauce",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2022/08/zapechennyj-losos.jpg.webp",
                            Price = 199m,
                            Title = "Baked Salmon",
                            Weight = 290.0
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            Consist = "salmon sous-vide, bell pepper, cucumber, cream cheese, Cheddar cheese, spice sauce",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2022/08/bayraktar-new.jpg.webp",
                            Price = 155m,
                            Title = "Bayraktar",
                            Weight = 210.0
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            Consist = "salmon, cream cheese, avocado, cucumber",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2021/01/filadelfiya-xl.jpg.webp",
                            Price = 225m,
                            Title = "Philadelphia XL",
                            Weight = 310.0
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            Consist = "salmon, snow crab, cucumber, takuan, campio, cream cheese, sauce",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2022/06/11-jamamoto-900h600-1.jpg.webp",
                            Price = 275m,
                            Title = "Yamamoto",
                            Weight = 305.0
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            Consist = "unagi perch, cream cheese, cucumber, unagi sauce, sesame",
                            Img = "https://roll-club.kh.ua/wp-content/uploads/2021/12/unagi-lajt.jpg.webp",
                            Price = 149m,
                            Title = "Philadelphia Unagi Light",
                            Weight = 210.0
                        });
                });

            modelBuilder.Entity("WebApi.Data.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApi.Data.Entities.OrderEntity", b =>
                {
                    b.HasOne("WebApi.Data.Entities.UserEntity", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApi.Data.Entities.OrderProductEntity", b =>
                {
                    b.HasOne("WebApi.Data.Entities.OrderEntity", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Data.Entities.ProductEntity", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApi.Data.Entities.ProductEntity", b =>
                {
                    b.HasOne("WebApi.Data.Entities.CategoryEntity", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebApi.Data.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebApi.Data.Entities.OrderEntity", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("WebApi.Data.Entities.ProductEntity", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("WebApi.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
